name: on-push-workflow
on: [push]
jobs:
  check-git-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show current directory
        run: ls -la
      - name: Show current branch
        run: git branch --show-current
